SPECIAL_SYMBOLS = {'exclam': '!', 'equal': '=', 'question': '?', 'space': " ", 'plus': '+', 'comma': ',',
                   'period': '.', 'minus': '-', 'underscore': '_', 'apostrophe': "'", 'colon': ':',
                   'semicolon': ';',
                   'parenleft': '(', 'parenright': ')', 'braceleft': '{', 'bracketleft': '[',
                   'braceright': '}', 'bracketright': ']', 'Cyrillic_SHORTI': 'Й', 'Cyrillic_TSE': 'Ц',
                   'Cyrillic_U': 'У', 'Cyrillic_KA': 'К', 'Cyrillic_IE': 'Е', 'Cyrillic_EN': 'Н',
                   'Cyrillic_GHE': 'Г', 'Cyrillic_SHA': 'Ш', 'Cyrillic_SHCHA': 'Щ', 'Cyrillic_ZE': 'З',
                   'Cyrillic_EF': 'Ф', 'Cyrillic_YERU': 'Ы', 'Cyrillic_VE': 'В', 'Cyrillic_A': 'А',
                   'Cyrillic_PE': 'П', 'Cyrillic_ER': 'Р', 'Cyrillic_O': 'О', 'Cyrillic_EL': 'Л',
                   'Cyrillic_DE': 'Д', 'Cyrillic_YA': 'Я', 'Cyrillic_CHE': 'Ч', 'Cyrillic_ES': 'С',
                   'Cyrillic_EM': 'М', 'Cyrillic_I': 'И', 'Cyrillic_TE': 'Т', 'Cyrillic_SOFTSIGN': 'Ь',
                   'Cyrillic_BE': 'Б', 'Cyrillic_YU': 'Ю', 'Cyrillic_shorti': 'й', 'Cyrillic_tse': 'ц',
                   'Cyrillic_u': 'у', 'Cyrillic_ka': 'к', 'Cyrillic_ie': 'е', 'Cyrillic_en': 'н',
                   'Cyrillic_ghe': 'г', 'Cyrillic_sha': 'ш', 'Cyrillic_shcha': 'щ', 'Cyrillic_ze': 'з',
                   'Cyrillic_ef': 'ф', 'Cyrillic_yeru': 'ы', 'Cyrillic_ve': 'в', 'Cyrillic_a': 'а',
                   'Cyrillic_pe': 'п', 'Cyrillic_er': 'р', 'Cyrillic_o': 'о', 'Cyrillic_el': 'л',
                   'Cyrillic_de': 'д', 'Cyrillic_ya': 'я', 'Cyrillic_che': 'ч', 'Cyrillic_es': 'с',
                   'Cyrillic_em': 'м', 'Cyrillic_i': 'и', 'Cyrillic_te': 'т', 'Cyrillic_softsign': 'ь',
                   'Cyrillic_be': 'б', 'Cyrillic_yu': 'ю', 'Cyrillic_ha': 'х', 'Cyrillic_hardsign': 'ъ',
                   'Cyrillic_zhe': 'ж', 'Cyrillic_e': 'э', 'Cyrillic_io': 'ё', 'Cyrillic_HA': 'Х',
                   'Cyrillic_HARDSIGN': 'Ъ', 'Cyrillic_ZHE': 'Ж', 'Cyrillic_E': 'Э', 'Cyrillic_IO': 'Ё'}
